### ISSUE TITLE
Using umd in the browser field breaks webpack 4

### ISSUE THREAD

**Issue by vibdev** [frehner/modern-guide-to-packaging-js-library#16]
I have my package.json set up as advised:
```json
{
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
  "browser": "dist/umd/index.min.js",
  "types": "dist/types/index.d.ts"
}
```
However, Webpack 4 has the highest priority for the browser entry. This causes the build to import the umd and throws a "Critical Dependency error." Could be wrong, but I think you would want Webpack to use commonjs (or even esm) for imports. Changing the browser field to the cjs file fixes it.

**Comment by frehner** [comment]
>Could be wrong, but I think you would want Webpack to use commonjs (or even esm) for imports. Changing the browser field to the cjs file fixes it.

The `browser` field is intended for code that can [run in the browser](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#browser), so having it point to a `.cjs` file / CommonJS bundle probably isn't the best. 

So it should probably be pointing to an esm bundle, I think? It's difficult to say, because it seems like webpack will use the `browser` field for what it bundles (so we want `esm` there), but other tools (e.g. `unpkg` I think) would prefer it to point to a `umd` bundle for script-tagging. 

Thoughts?

---

As a side note, if your library is universal, then you could probably [remove the browser field](https://github.com/webpack/webpack/issues/4674#issuecomment-537764550) and let webpack 4 use the `module` field instead.

---

Finally, this does have me wondering about the order of the `browser` field in the package exports as well - maybe it should go after the `module` field?

**Comment by frehner** [comment]
I've done quite a bit of testing in Vite, which uses Rollup's node-resolution plugin. Turns out they don't look at the `browser` field at all by default, and _never_ look at it when you use package exports. https://github.com/rollup/plugins/tree/master/packages/node-resolve/#browser

So that's why I've missed this behavior in webpack 4.

**Comment by vibdev** [comment]
> As a side note, if your library is universal, then you could probably https://github.com/webpack/webpack/issues/4674#issuecomment-537764550 and let webpack 4 use the module field instead.

I think this will work in my case 👍  
Was thinking it would be nice to serve minified code to the browser and non minified code to webpack, for better tree shaking, but maybe that is not possible without upgrading to something that understands exports, webpack 5, vite, etc.

**Comment by vibdev** [comment]
> These type of compressions are generally _not_ run by minifiers on NPM modules, and therefore you will miss out on those savings unless you do it yourself. 

But maybe I am thinking about it wrong and should just be minifying everything anyway?

**Comment by frehner** [comment]
I'll spin up a project with webpack 5 and see how it handles things, and update the `browser` recommendations from there. 

>But maybe I am thinking about it wrong and should just be minifying everything anyway?

They're generally pretty small, but if you are absolutely dead focused on minimum bytes and are willing to put in the effort to get them, then yeah you could minify yourself. (e.g. Preact is an excellent example of this)

**Comment by frehner** [comment]
Confirmed that webpack 4 prioritizes `package.json#browser`

Confirmed that webpack 5 prioritizes `package.json#exports` `browser` entry.

So yeah, I'm going to update the `browser` field recommendations

**Comment by frehner** [comment]
The browser fields should be used for code going into the browser, but should probably be `esm` instead of `umd`.  

If you code is universal, then you can exclude it. 

https://github.com/defunctzombie/package-browser-field-spec#notes

And then use `package.json#unpkg` or similar for the `umd` bundles. I'll start writing up the update now.

**Comment by vibdev** [comment]
Thanks for the quick testing! This project is so great. Anything to help demystify the boundless config of a javascript project is really appreciated.
